/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.h7g7.service.base;

import com.liferay.h7g7.model.H7G7Folder;
import com.liferay.h7g7.service.H7G7FolderLocalService;
import com.liferay.h7g7.service.H7G7FolderLocalServiceUtil;
import com.liferay.h7g7.service.persistence.H7G7EntryPersistence;
import com.liferay.h7g7.service.persistence.H7G7FolderPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the h7g7 folder local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.h7g7.service.impl.H7G7FolderLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.h7g7.service.impl.H7G7FolderLocalServiceImpl
 * @generated
 */
public abstract class H7G7FolderLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, H7G7FolderLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>H7G7FolderLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>H7G7FolderLocalServiceUtil</code>.
	 */

	/**
	 * Adds the h7g7 folder to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect H7G7FolderLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param h7g7Folder the h7g7 folder
	 * @return the h7g7 folder that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public H7G7Folder addH7G7Folder(H7G7Folder h7g7Folder) {
		h7g7Folder.setNew(true);

		return h7g7FolderPersistence.update(h7g7Folder);
	}

	/**
	 * Creates a new h7g7 folder with the primary key. Does not add the h7g7 folder to the database.
	 *
	 * @param h7g7FolderId the primary key for the new h7g7 folder
	 * @return the new h7g7 folder
	 */
	@Override
	@Transactional(enabled = false)
	public H7G7Folder createH7G7Folder(long h7g7FolderId) {
		return h7g7FolderPersistence.create(h7g7FolderId);
	}

	/**
	 * Deletes the h7g7 folder with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect H7G7FolderLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param h7g7FolderId the primary key of the h7g7 folder
	 * @return the h7g7 folder that was removed
	 * @throws PortalException if a h7g7 folder with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public H7G7Folder deleteH7G7Folder(long h7g7FolderId)
		throws PortalException {

		return h7g7FolderPersistence.remove(h7g7FolderId);
	}

	/**
	 * Deletes the h7g7 folder from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect H7G7FolderLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param h7g7Folder the h7g7 folder
	 * @return the h7g7 folder that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public H7G7Folder deleteH7G7Folder(H7G7Folder h7g7Folder) {
		return h7g7FolderPersistence.remove(h7g7Folder);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return h7g7FolderPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			H7G7Folder.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return h7g7FolderPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.h7g7.model.impl.H7G7FolderModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return h7g7FolderPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.h7g7.model.impl.H7G7FolderModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return h7g7FolderPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return h7g7FolderPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return h7g7FolderPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public H7G7Folder fetchH7G7Folder(long h7g7FolderId) {
		return h7g7FolderPersistence.fetchByPrimaryKey(h7g7FolderId);
	}

	/**
	 * Returns the h7g7 folder with the primary key.
	 *
	 * @param h7g7FolderId the primary key of the h7g7 folder
	 * @return the h7g7 folder
	 * @throws PortalException if a h7g7 folder with the primary key could not be found
	 */
	@Override
	public H7G7Folder getH7G7Folder(long h7g7FolderId) throws PortalException {
		return h7g7FolderPersistence.findByPrimaryKey(h7g7FolderId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(h7g7FolderLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(H7G7Folder.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("h7g7FolderId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			h7g7FolderLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(H7G7Folder.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"h7g7FolderId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(h7g7FolderLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(H7G7Folder.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("h7g7FolderId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return h7g7FolderPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return h7g7FolderLocalService.deleteH7G7Folder(
			(H7G7Folder)persistedModel);
	}

	@Override
	public BasePersistence<H7G7Folder> getBasePersistence() {
		return h7g7FolderPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return h7g7FolderPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the h7g7 folders.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.h7g7.model.impl.H7G7FolderModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of h7g7 folders
	 * @param end the upper bound of the range of h7g7 folders (not inclusive)
	 * @return the range of h7g7 folders
	 */
	@Override
	public List<H7G7Folder> getH7G7Folders(int start, int end) {
		return h7g7FolderPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of h7g7 folders.
	 *
	 * @return the number of h7g7 folders
	 */
	@Override
	public int getH7G7FoldersCount() {
		return h7g7FolderPersistence.countAll();
	}

	/**
	 * Updates the h7g7 folder in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect H7G7FolderLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param h7g7Folder the h7g7 folder
	 * @return the h7g7 folder that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public H7G7Folder updateH7G7Folder(H7G7Folder h7g7Folder) {
		return h7g7FolderPersistence.update(h7g7Folder);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			H7G7FolderLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		h7g7FolderLocalService = (H7G7FolderLocalService)aopProxy;

		_setLocalServiceUtilService(h7g7FolderLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return H7G7FolderLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return H7G7Folder.class;
	}

	protected String getModelClassName() {
		return H7G7Folder.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = h7g7FolderPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		H7G7FolderLocalService h7g7FolderLocalService) {

		try {
			Field field = H7G7FolderLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, h7g7FolderLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected H7G7EntryPersistence h7g7EntryPersistence;

	protected H7G7FolderLocalService h7g7FolderLocalService;

	@Reference
	protected H7G7FolderPersistence h7g7FolderPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}