/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.h7g7.model.impl;

import com.liferay.h7g7.model.H7G7Folder;
import com.liferay.h7g7.service.H7G7FolderLocalServiceUtil;

/**
 * The extended model base implementation for the H7G7Folder service. Represents a row in the &quot;OHQIWTSFHL_H7G7Folder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link H7G7FolderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see H7G7FolderImpl
 * @see H7G7Folder
 * @generated
 */
public abstract class H7G7FolderBaseImpl
	extends H7G7FolderModelImpl implements H7G7Folder {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a h7g7 folder model instance should use the <code>H7G7Folder</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			H7G7FolderLocalServiceUtil.addH7G7Folder(this);
		}
		else {
			H7G7FolderLocalServiceUtil.updateH7G7Folder(this);
		}
	}

}