/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.h7g5.model.impl;

import com.liferay.h7g5.model.H7G5Folder;
import com.liferay.h7g5.service.H7G5FolderLocalServiceUtil;

/**
 * The extended model base implementation for the H7G5Folder service. Represents a row in the &quot;OHQIWTSFHL_H7G5Folder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link H7G5FolderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see H7G5FolderImpl
 * @see H7G5Folder
 * @generated
 */
public abstract class H7G5FolderBaseImpl
	extends H7G5FolderModelImpl implements H7G5Folder {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a h7g5 folder model instance should use the <code>H7G5Folder</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			H7G5FolderLocalServiceUtil.addH7G5Folder(this);
		}
		else {
			H7G5FolderLocalServiceUtil.updateH7G5Folder(this);
		}
	}

}